//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace u16073861_INF354_HW1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditTrail
    {
        public int AuditTrailID { get; set; }
        public int User_ID { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public string TransactionDescription { get; set; }
        public string TransactionType { get; set; }
    
        public virtual User User { get; set; }
    }
}
