//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace u16073861_INF354_HW1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Competition
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Competition()
        {
            this.Performances = new HashSet<Performance>();
            this.Technician_Competition_League_Season_Event = new HashSet<Technician_Competition_League_Season_Event>();
        }
    
        public int Competition_ID { get; set; }
        public int Club_ID { get; set; }
        public int District_ID { get; set; }
        public int Venue_ID { get; set; }
        public int CompetitionType_ID { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual Club Club { get; set; }
        public virtual CompetitionType CompetitionType { get; set; }
        public virtual District District { get; set; }
        public virtual Venue Venue { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Performance> Performances { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Technician_Competition_League_Season_Event> Technician_Competition_League_Season_Event { get; set; }
    }
}
