//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace u16073861_INF354_HW1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Tuks_Athletics_SystemEntities : DbContext
    {
        public Tuks_Athletics_SystemEntities()
            : base("name=Tuks_Athletics_SystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Access> Accesses { get; set; }
        public virtual DbSet<Access_Level> Access_Level { get; set; }
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<Age_Group> Age_Group { get; set; }
        public virtual DbSet<Athlete> Athletes { get; set; }
        public virtual DbSet<AuditTrail> AuditTrails { get; set; }
        public virtual DbSet<Banned_Substance> Banned_Substance { get; set; }
        public virtual DbSet<Club> Clubs { get; set; }
        public virtual DbSet<Coach> Coaches { get; set; }
        public virtual DbSet<Competition> Competitions { get; set; }
        public virtual DbSet<CompetitionType> CompetitionTypes { get; set; }
        public virtual DbSet<District> Districts { get; set; }
        public virtual DbSet<Event> Events { get; set; }
        public virtual DbSet<EventType> EventTypes { get; set; }
        public virtual DbSet<Exercise> Exercises { get; set; }
        public virtual DbSet<Federation> Federations { get; set; }
        public virtual DbSet<Functionality> Functionalities { get; set; }
        public virtual DbSet<Gender> Genders { get; set; }
        public virtual DbSet<Heat> Heats { get; set; }
        public virtual DbSet<League> Leagues { get; set; }
        public virtual DbSet<Medal> Medals { get; set; }
        public virtual DbSet<Performance> Performances { get; set; }
        public virtual DbSet<Program> Programs { get; set; }
        public virtual DbSet<Record> Records { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Season> Seasons { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<Technician> Technicians { get; set; }
        public virtual DbSet<Test_Result> Test_Result { get; set; }
        public virtual DbSet<TestType> TestTypes { get; set; }
        public virtual DbSet<Unit> Units { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserType> UserTypes { get; set; }
        public virtual DbSet<Venue> Venues { get; set; }
        public virtual DbSet<Athlete_Event_Program> Athlete_Event_Program { get; set; }
        public virtual DbSet<Athlete_Season_Event> Athlete_Season_Event { get; set; }
        public virtual DbSet<Coach_Event_Program_Exercise> Coach_Event_Program_Exercise { get; set; }
        public virtual DbSet<Federation_Event_Record> Federation_Event_Record { get; set; }
        public virtual DbSet<Technician_Competition_League_Season_Event> Technician_Competition_League_Season_Event { get; set; }
    }
}
