//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace u16073861_INF354_HW1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Performance
    {
        public int Athlete_ID { get; set; }
        public int Heat_ID { get; set; }
        public int Event_ID { get; set; }
        public int Medal_ID { get; set; }
        public int Age_ID { get; set; }
        public int Competition_ID { get; set; }
        public string Result { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public int Performance_ID { get; set; }
        public Nullable<int> Point { get; set; }
    
        public virtual Age_Group Age_Group { get; set; }
        public virtual Athlete Athlete { get; set; }
        public virtual Competition Competition { get; set; }
        public virtual Event Event { get; set; }
        public virtual Heat Heat { get; set; }
        public virtual Medal Medal { get; set; }
    }
}
