//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace u16073861_INF354_HW1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Record
    {
        public int Record_ID { get; set; }
        public int Event_ID { get; set; }
        public int Athlete_ID { get; set; }
        public int Unit_ID { get; set; }
        public string Record1 { get; set; }
    
        public virtual Athlete Athlete { get; set; }
        public virtual Event Event { get; set; }
        public virtual Unit Unit { get; set; }
    }
}
