//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace u16073861_INF354_HW1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Technician_Competition_League_Season_Event
    {
        public int Technician_ID { get; set; }
        public int Competition_ID { get; set; }
        public int League_ID { get; set; }
        public int Season_ID { get; set; }
        public int Event_ID { get; set; }
    
        public virtual Competition Competition { get; set; }
        public virtual Event Event { get; set; }
        public virtual League League { get; set; }
        public virtual Season Season { get; set; }
        public virtual Technician Technician { get; set; }
    }
}
