//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace u16073861_INF354_HW1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Technician
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Technician()
        {
            this.Technician_Competition_League_Season_Event = new HashSet<Technician_Competition_League_Season_Event>();
        }
    
        public int Technician_ID { get; set; }
        public int User_ID { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Experience { get; set; }
        public string Phone_Number { get; set; }
        public string Email { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Technician_Competition_League_Season_Event> Technician_Competition_League_Season_Event { get; set; }
        public virtual User User { get; set; }
    }
}
