//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace u16073861_INF354_HW1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserType
    {
        public int Type_ID { get; set; }
        public int User_ID { get; set; }
        public int Access_Level { get; set; }
    
        public virtual Access_Level Access_Level1 { get; set; }
        public virtual User User { get; set; }
    }
}
